# Generated by Django 5.1 on 2024-08-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('appearance', models.CharField(blank=True, max_length=100)),
                ('personality', models.CharField(blank=True, max_length=100)),
                ('backstory', models.CharField(blank=True, max_length=300)),
                ('power_source', models.CharField(choices=[('Stand User', 'Stand User'), ('Hamon Warrior', 'Hamon Warrior'), ('Vampire', 'Vampire'), ('Spin Master', 'Spin Master'), ('Armed Phenomenon', 'Armed Phenomenon'), ('No Power Source', 'No Power Source')], default='No Power Source', max_length=30)),
                ('power_source_design', models.CharField(blank=True, max_length=100)),
                ('power_source_abilities', models.CharField(blank=True, max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('scene', models.ManyToManyField(to='scenes.scene')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(choices=[('Body', 'Body'), ('Reason', 'Reason'), ('Wit', 'Wit'), ('Menacing', 'Menacing'), ('Pluck', 'Pluck'), ('Luck', 'Luck')], max_length=10)),
                ('stat_rank', models.CharField(choices=[('0', 'Automatic failure'), ('E', '1d6'), ('D', '2d6'), ('C', '3d6'), ('B', '4d6'), ('A', '5d6'), ('S', 'Special')], max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='PowerSourceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(choices=[('Power', 'Power'), ('Speed', 'Speed'), ('Range', 'Range'), ('Durability', 'Durability'), ('Presicion', 'Presicion'), ('Potential', 'Potential')], max_length=10)),
                ('stat_rank', models.CharField(choices=[('0', 'Automatic failure'), ('E', '1d6'), ('D', '2d6'), ('C', '3d6'), ('B', '4d6'), ('A', '5d6'), ('S', 'Special')], max_length=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_stats', to='characters.character')),
            ],
        ),
    ]
