# Generated by Django 5.1 on 2024-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='scene',
        ),
        migrations.AlterField(
            model_name='character',
            name='power_source',
            field=models.CharField(choices=[('Stand User', 'Stand User'), ('Hamon Warrior', 'Hamon Warrior'), ('Vampire', 'Vampire'), ('Spin Master', 'Spin Master'), ('Armed Phenomenon', 'Armed Phenomenon'), ('Cyborg', 'Cyborg'), ('Multiple Power Sources', 'Multiple Power Sources'), ('No Power Source', 'No Power Source')], default='No Power Source', max_length=30),
        ),
    ]
