# Generated by Django 5.1 on 2024-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_character_scene_alter_character_power_source'),
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='characters',
            field=models.ManyToManyField(to='characters.character'),
        ),
    ]
